### ISSUE TITLE
Single character selectors are removed even if they are used

### ISSUE THREAD

**Issue by maoberlehner** [vokal/declassify#4]
```css
.c { color: blue; }
```

```html
<div class="c">Lorem Ipsum</div>
```

The `.c` selector is removed although it is used.

**Comment by maoberlehner** [comment]
I added a merge request which fixes this issue, although this Regex also isn't correct because CSS selectors allow for almost all characters if they are escaped (e.g. `.some-selector\@breakpoint-s`).

Handling all those cases would be rather complicated and I guess the best way to handle this perfectly would be to do it in a similar way to how it is done by UnCSS: using JSDom and postcss.

Would you be OK if I go in this direction and if I maybe open a rather huge pull request at some point in the future?

**Comment by jrit** [comment]
To address your question, it sounds like you are thinking about making the regex work better for invalid CSS. My feeling is garbage-in -> garbage-out, so probably isn't worth your time to make the overhaul IMO.
