### ISSUE TITLE
Single quote marks within HTML are returned as &apos; breaks in outlook emails

### ISSUE THREAD

**Issue by jjblumenfeld** [vokal/declassify#7]
When the original HTML text contains an unencoded single quote mark it is returned from declassify with the quote-mark encoded as &apos;.
This does not display as a single-quote within outlook but renders as the literal string &apos;.

**Comment by jjblumenfeld** [comment]
PR submitted:
https://github.com/jrit/declassify/pull/6

**Comment by jrit** [comment]
closed by #6
